### ISSUE TITLE
Potential helper script cross-platform issues

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#103]

**Comment by int00h5525** [comment]
helper.js may not work correctly on some otherwise-supported browsers?

**Comment by nealey** [comment]
It had a problem in Firefox that I fixed in https://github.com/dirtbags/moth/commit/30754fa8e9f877cc4f1bf235f78aa308d88bb1dc.

If we find another problem, let's document the browser that's having the problem, and what the problem is :)
