### ISSUE TITLE
Sort points.log

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#107]
Maintenance can generate out-of order points.log

**Comment by pi-rho** [comment]
Its in time-order. what conditions make it out of order?

**Comment by int00h5525** [comment]
> Its in time-order. what conditions make it out of order?

`collectPoints` blindly sucks up point records in `points.new/` in the order returned by `ioutil.ReadDir` (alphabetically by filename) and appends them to `points.log` without validating that the timestamps provided in the `points.new/` entries increase monotonically. If using the legacy `awardPoints` script, filenames are generated using the current timestamp, but mothd generates filenames using the pattern `teamId-category-points`. The rate of submission is low enough and current mothd implementation is fast enough that submissions are usually processed near-instantaneously, but, if more than one submission were to arrive at a close enough interval that multiple were processed by the same `collectPoints` routine, or the game were paused for a period of time in which multiple points were submitted, it is possible that they would be read in and appended out of chronological order.

**Comment by int00h5525** [comment]
Closed in #135
