### ISSUE TITLE
Only store scoreboard updates

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#110]
Only store scoreboard unique updates in localstorage, not repeated identical updates

**Comment by pi-rho** [comment]
where does the diff happen? or is it more of a journal, where client asks for updates since a timestamp? do you think diffing client side is more expensive in processing than the storage saved? do you want the server processing requested score updates for every client?

**Comment by nealey** [comment]
John is talking here about the use of localStorage to store state pulls.

Given how small these pulls are relative to, say, a medium-sized JPEG, I'm going to decline to implement all this differential logic.
