### ISSUE TITLE
Do away with `state/disabled`

### ISSUE THREAD

**Issue by nealey** [dirtbags/moth#112]
v4 has a new, robust `state/hours` file that can specify begin and end hours. Because of the way it's parsed, the following commands are equivalent:

| v3 command | v4 command |
| --- | --- |
| touch state/disabled | echo - >> state/hours |
| rm state/disabled | echo + >> state/hours |

I propose we do away with the `disabled` file and use `state/hours` exclusively for determining whether the event is active.

**Comment by int00h5525** [comment]
I think that we should keep `disabled`, since there are other reasons to disable an event, like hot-patching the state, pausing during a meal, or waiting for a non-time-gated event to start/stop an event (everyone in the class has given a thumbs-up, so we can start, etc.)

**Comment by int00h5525** [comment]
Sorry, just seeing the equivalence, now. What is the expected format of `state/hours`? Would using the syntax that you provided above break any scheduled start/stop times?

**Comment by nealey** [comment]
Lines are:

| regexp | description |
| --- | --- |
| `^$` | ignored |
| `^#` | comment (ignored) |
| `+[:space:]*[:rfc3339:]?` | enable time |
| `-[:space:]*[:rfc3339:]?` | disable time |
| fallthrough | emit warning and keep parsing file |

File is parsed line by line. Any times that are before the current time modify the state, so the last one wins. No time means "always matches".

**Comment by pi-rho** [comment]
what if you don't have a specific time that you want it on or off? would you consider crontab-style or splunk-style relative words? (i.e. +2h@h, meaning two hours after the current hour [splunk style]; or @tomorrow-0800 [sort of crontab :/])

Also, is this forced to Zulu time or is it just server-time, whatever zone that might be?

**Comment by nealey** [comment]
> No time string is equivalent to Unix time 0

old | new
---|---
touch disabled | echo - >> hours
rm disabled | echo + >> hours

If we keep the existing functionality I am at least going to rename it from `disabled` to `enabled`, so all the magic files exist by default and have a little documentation inside.

**Comment by nealey** [comment]
Okay actually, doing the `echo - >> hours` would blow away the previously-entered stop time, which would have the effect of undoing your carefully-crafted schedule.

I'll just change `disabled` to `enabled` (and invert the logic, of course)
