### ISSUE TITLE
Move HTML out of `puzzle.json` in mothballs

### ISSUE THREAD

**Issue by nealey** [dirtbags/moth#113]
I would like to break the puzzle HTML out into `index.html` instead of encoding it into `puzzle.json`. This would make `puzzle.json` a metadata structure, with answers, KPIs, hints, whatever else, and `index.html` becomes just another file that can be requested by the client.

**Comment by pi-rho** [comment]
Already requested in #54, essentially.

**Comment by int00h5525** [comment]
> Already requested in #54, essentially.

#54 is a step in the opposite direction, by embedding more content into puzzle.json, instead of what this suggests, in separating content, such as HTML and Markdown, from metadata, which solely would live in puzzle.json

**Comment by pi-rho** [comment]
what if the markdown stays in puzzle.json, but clients can ask for rendered content?

**Comment by nealey** [comment]
Okay I'm going to weigh in here and swing my mighty club.

We will be sticking with HTML5 in the object, which has the benefit of being standardized, has decades of experience informing its design, and in 2020 is pretty unambiguously rendered in every rendering engine. Markdown has multiple translators with incompatible extensions, and it's really the best of breed for markup that isn't HTML5. Not only that, we've got 11 years worth of content now: lots of it is in Markdown, true; but some very key stuff uses Markdown's "you can drop HTML in here if you need it".

If somebody wants Markdown versions of the puzzles, they're going to have to convert from HTML5. Sorry.

**Comment by nealey** [comment]
In case it wasn't clear, there will be no changes in this regard.
