### ISSUE TITLE
mothd is a WebDAV provider

### ISSUE THREAD

**Issue by nealey** [dirtbags/moth#114]
Without too much extra work (`PROPFIND` is a ridiculous mess, but we can figure it out), v4's HTTP API could be a WebDAV server. This would allow weirdos like @pi-rho to *mount* the puzzle server (and `rsync` it, if they want). Weirdos like me could write a set of scripts so you could use [Acme](https://en.wikipedia.org/wiki/Acme_(text_editor)) as a client. And of course we could still have an HTML5 client.

`find` on a mounted server would look something like:

```sh
/event/state/active # true or false
/event/state/teams/0/name # echo My Cool Team Name > state/teams/0/name
/event/state/teams/1/name
/event/state/teams/2/name
/event/state/points.log # Same format as server-side, with anonymized team IDs
/event/puzzles/sequence/answer # echo 1 myanswer > puzzles/sequence/answer
/event/puzzles/sequence/1/answer  # echo myanswer > puzzles/sequence/1/answer
/event/puzzles/sequence/1/puzzle.json
/event/puzzles/sequence/1/index.html
/event/puzzles/sequence/1/attachment.jpg
```

The HTTP interface would be really similar. We currently have only two (!) "write" API endpoints, which would become:

* `curl --data "My Cool Team Name" https://puzzles/event/state/teams/0/name` to register your team
* `curl --data "1 myanswer" https://puzzles/event/puzzles/sequence/answer` to submit an answer

A few fundamental changes fall out of this:

* No more of the hashing puzzle directories to hide them: the server either shows the 5 point puzzle (if it's unlocked) or it doesn't.
* WebDAV directory listings would suffice to see what puzzles are open. We could provide some sort of functionality where if you `GET` a directory, it automatically provides a recursive listing.
* We don't need `puzzles.json` anymore.

Some things I haven't thought about too hard but seem not difficult to work out:

* How do we get the Team ID sent in? Querystring probably.
* How do we serve up `themes`? Split API off from serving the HTML client program? This seems to be a common design practice nowadays.
* We need a way to communicate "the answer you submitted is wrong" through the FS. Some sort of error on file close, perhaps.
* "tokens" are a tiny bit more challenging with a filesystem (but we could provide a "submit-token.sh" script that pulls them apart and writes into the right file).

**Comment by int00h5525** [comment]
> How do we get the Team ID sent in? Querystring probably.
HTTP Authorization header

**Comment by pi-rho** [comment]
FWIW, *I* don't want to mount the puzzle server. I don't usually `rsync`. I do appreciate interacting with the puzzle server from the command line where I do work, instead of a browser.

That being said, industry has produced fuse mounts to enable command-line interaction with what might be a complex API (I'm thinking of Solera's full packet capture and index appliances <3). It's really neat to interact with a service that way.

**Comment by nealey** [comment]
After further consideration, I now think this is a silly idea. It would require a bunch of extra code in both the client and the server, to support a protocol nobody particularly likes, and is a use case that nobody actually wants.

If we're going to make it show up as a filesystem, we should support 9p instead. And we're not going to be doing that.
