### ISSUE TITLE
Include version information in mothballs

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#115]
Should we version the mothball spec and track it in each mothball with something like `VERSION`? Maybe the version of the devel server? This may be useful if we have either formatting changes or features in mothballs that break or aren't fully supported by some versions of mothd or the devel server. For example, if we build in regex-based grading, even if it doesn't break mothd, it may cause unexpected results when run on an older version, and it would be nice to flag mothballs which may have potential compatibility issues.

**Comment by pi-rho** [comment]
It'd be better to start using the idea of an API/ABI versioning system. It's an agreement that acts as an interface between the code and users of its endpoints/products. It also leads to healthier design. Once that is done, definitely mark any products from the devel server with whatever ABI version it's using. Any API codepoints from the production server should advertise their API versions. Then clients can be written that can gracefully degrade if the server is less capable than the client.
