### ISSUE TITLE
Remove the weird block on viewing the scoreboard

### ISSUE THREAD

**Issue by pi-rho** [dirtbags/moth#116]
This was added as an avoidance of being blocked by some "security" provider. It turned out to be nothing at all related to why the block happened. Its weird. It's awkward. It totally broke one of my precious scripts. ;)

**Comment by int00h5525** [comment]
The scoreboard already can be viewed without logging in. Only the puzzle listing and puzzle content are locked down.

**Comment by pi-rho** [comment]
okay, remove all blocks. undo what was done to avoid being blocked by reputation services.
