### ISSUE TITLE
Integrate category-munging

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#131]
Allow better organization of categories by permitting developers to do something like the below
```
mycategory/
  subcategory1/
    1/puzzle.moth
    3/puzzle.py
  subcategory2/
    2/puzzle.py
  subcategory3/
    category.py (generates 10-20)
```

which would generate a category, `mycategory`, with points 1,2,3, and 10-20

**Comment by nealey** [comment]
Implemented in v4 as an example `mkcategory`, with the notable exception of a nested `mkcategory`, which is left as an exercise to the reader.

https://github.com/dirtbags/moth/blob/main/example-puzzles/mkcategory/mkcategory
