### ISSUE TITLE
Track participation metrics

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#143]
## Summary

Add some features to make it easier to track participation, such as puzzle load and solution times.

## Motivation

Need better metrics collection that doesn't rely on parsing server access logs.

## Describe alternatives you've considered

* External logging: requires more work to tune
* Internal logging: removes some disk-usage guarantees

## Additional context

Write out `state/teams/$id/$category.$points.load` and `state/teams/$id/$category.$points.solved` with JSON metadata, initially containing timestamp and participant ID, if provided

**Comment by nealey** [comment]
This was added to v4, in a format that can be easily pulled into a spreadsheet by our data analyst person.

https://github.com/dirtbags/moth/blob/main/docs/logs.md#eventslog-format
