### ISSUE TITLE
Submit-time grading support

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#31]
Instead of generating a static list of acceptable answers at compile time, grade submissions at submission time against grading code. This would make it easier to create puzzles like "X + Y =10" or "What is the current minute" or puzzles in which multiple valid capitalizations might exist.

**Comment by nealey** [comment]
Out of scope (see item 2 in https://github.com/dirtbags/moth/blob/master/docs/philosophy.md)

You could create a server-side oracle that grades answers and returns valid tokens if they're correct, but you'd need to do this out of the MOTH tree.
