### ISSUE TITLE
tcpserver: illegal option -- I

### ISSUE THREAD

**Issue by jwernicke** [dirtbags/moth#36]
https://github.com/dirtbags/moth/blob/17859eeb610ab90418c5609783e933c07a0d2354/bin/httpd#L15

I'm using the Raspbian Stretch `ucspi-tcp`. I created a `www` user/group like in the [eris Dockerfile](https://github.com/nealey/eris/blob/master/Dockerfile). I can start up a standalone eris server and serve out files just fine, but when I try to use `/moth/bin/httpd`:
```
pi@smartcap:/srv/moth/spark18 $ sudo bin/httpd
Figuring out web user...
uid=800(www) gid=800(www) groups=800(www)
tcpserver: illegal option -- I
tcpserver: usage: tcpserver [ -1UXpPhHrRoOdDqQv ] [ -c limit ] [ -x rules.cdb ] [ -B banner ] [ -g gid ] [ -u uid ] [ -b backlog ] [ -l localname ] [ -t timeout ] host port program
```
I don't know what the `I` flag is supposed to do, but if I remove it from the script:
```
pi@smartcap:/srv/moth/spark18 $ sudo bin/httpd
Figuring out web user...
uid=800(www) gid=800(www) groups=800(www)
tcpserver: fatal: unable to figure out port number for -u
```
Which also happens to be the error I get if I use `www-data` and leave the `I` flag in there.

**Comment by nealey** [comment]
Obviated with MOTHv3
