### ISSUE TITLE
Update README on Dockerhub

### ISSUE THREAD

**Issue by 3ch01c** [dirtbags/moth#55]
Launching example on [Dockerhub page](https://hub.docker.com/r/dirtbags/moth/) should be:
```
docker run --rm -v /path/to/mothballs:/mothballs:ro -v /path/to/state:/state -p 8080:8080 dirtbags/moth
```

**Comment by nealey** [comment]
Done, thanks.

If you or any other core devs have a Docker Hub account I will add you to the dirtbags team.
