### ISSUE TITLE
Support downloading open content

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#81]
We need some way to download all currently-open content as a single ZIP file, in case something happens to the network

**Comment by nealey** [comment]
This will probably be the same as #68

**Comment by int00h5525** [comment]
Code was written in experimental dehydrator module https://github.com/dirtbags/moth/blob/95bcc860e0f49091ba73f14778dde4be8db7d7c5/src/handlers.go#L255 . Do we still want this to stand apart from the PWA caching to allow participants to download content?

**Comment by nealey** [comment]
This is really close now. Between `attachments` and `scripts`, we're now serving up everything you need to get a full download. At least, if you use the transpiler to make your mothballs.

**Comment by nealey** [comment]
Next steps:

- Write something to pull the state, then pull each puzzle, then pull all attachments and scripts. It can use https.

**Comment by nealey** [comment]
Server support for this is complete, and this is now implemented in the cyber fire client (HTML only for now, no attachments).
