### ISSUE TITLE
Clarify potentially-correct solutions

### ISSUE THREAD

**Issue by int00h5525** [dirtbags/moth#98]
The current question-mark icon for potentially-correct solutions isn't always immediately obvious, and some people don't see the hover text. Might something else (a person-shrugging emoji?) be more clear?

**Comment by pi-rho** [comment]
maybe hot/cold icons?

**Comment by nealey** [comment]
I've changed it to ❌ and ⭕ in the new netarch theme, after reading that they have roughly the meanings we want in Japan. I think they work better. Without using words I don't think we'll ever be able to clearly communicate "this could be correct or it could be a hash collision".

I've been searching off and on for suitable Unicode glyphs for over a year now. I think this is the best we're going to get, but I'll leave the issue open a few more months in case anybody has a spark of inspiration. If not, we'll move to ❌ and ⭕.

**Comment by nealey** [comment]
❌ and ⭕ appear to be doing the job.
